# Generated by Django 2.2.5 on 2019-10-16 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CARD_ID', models.CharField(max_length=10, verbose_name='身分證號碼')),
                ('NAME', models.CharField(max_length=10, verbose_name='姓名')),
                ('USERNAME', models.CharField(max_length=16, verbose_name='帳號')),
                ('PASSWORD', models.CharField(max_length=256, verbose_name='密碼')),
                ('BIRTHDAY', models.DateField(verbose_name='生日')),
                ('BLOOD', models.CharField(max_length=1, verbose_name='血型')),
                ('ADDRESS', models.CharField(max_length=64, verbose_name='住址')),
                ('TEL', models.CharField(max_length=10, verbose_name='聯絡電話')),
                ('MOBILE', models.CharField(max_length=10, verbose_name='行動電話')),
                ('CONTACT', models.CharField(max_length=10, verbose_name='緊急聯絡人')),
                ('CONTACT_TEL', models.CharField(max_length=10, verbose_name='聯絡人電話')),
                ('CONTACT_RELATION', models.CharField(max_length=10, verbose_name='聯絡人關係')),
                ('FIRST_CAREER', models.CharField(max_length=10, verbose_name='第一份職業')),
                ('LAST_CAREER', models.CharField(max_length=10, verbose_name='最後一份職業')),
                ('ROOM', models.CharField(max_length=10, verbose_name='房號')),
                ('IS_STAFF', models.BooleanField(verbose_name='職員')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
