# Generated by Django 2.2.5 on 2019-10-16 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEPARTMENT', models.CharField(max_length=10, verbose_name='科別')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ADDRESS',
            field=models.CharField(max_length=64, null=True, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='BLOOD',
            field=models.CharField(max_length=1, null=True, verbose_name='血型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='CONTACT',
            field=models.CharField(max_length=10, null=True, verbose_name='緊急聯絡人'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='CONTACT_RELATION',
            field=models.CharField(max_length=10, null=True, verbose_name='聯絡人關係'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='CONTACT_TEL',
            field=models.CharField(max_length=10, null=True, verbose_name='聯絡人電話'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='FIRST_CAREER',
            field=models.CharField(max_length=10, null=True, verbose_name='第一份職業'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='LAST_CAREER',
            field=models.CharField(max_length=10, null=True, verbose_name='最後一份職業'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='MOBILE',
            field=models.CharField(max_length=10, null=True, verbose_name='行動電話'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ROOM',
            field=models.CharField(max_length=10, null=True, verbose_name='房號'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='TEL',
            field=models.CharField(max_length=10, null=True, verbose_name='聯絡電話'),
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(null=True, verbose_name='回診日')),
                ('number', models.IntegerField(verbose_name='回診號碼')),
                ('date2', models.DateField(null=True, verbose_name='第三次處方簽領藥日')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Department', to='app1.Department', verbose_name='科別')),
            ],
        ),
    ]
