# Generated by Django 2.2.5 on 2019-10-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20191017_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='DOCTOR',
            field=models.CharField(max_length=10, null=True, verbose_name='醫師'),
        ),
    ]
