# Generated by Django 2.2.5 on 2019-10-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_department_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='date3',
            field=models.DateField(null=True, verbose_name='第三次處方簽領藥日'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='date2',
            field=models.DateField(null=True, verbose_name='第二次處方簽領藥日'),
        ),
    ]
